server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat/**
        - id: notice-service
          uri: lb://NOTICE-SERVICE
          predicates:
            - Path=/notice/**
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member/**
        - id: channel-service
          uri: lb://CHANNEL-SERVICE
          predicates:
            - Path=/channel/**
        - id: search-service
          uri: lb://SEARCH-SERVICE
          predicates:
            - Path=/search/**